[build]
command = 'npm run build'
functions = './functions'
publish = '/build'

[[redirects]]
from = '/api/*'
status = 200
to = '/.netlify/functions/:splat'

[[redirects]]
from = '/*'
status = 200
to = '/index.html'
